<?php

function imagewebimport_menu() {

  $items['admin/t'] = array(
    'title' => 'imagewebimport',
    'page callback' => 'imagewebimport_create',
    'access arguments' => array('access content'),
    'type' => MENU_CALLBACK    
  );

  return $items;
}

function imagewebimport_create() {
    
    if(isset($_REQUEST['get_article']) && $_REQUEST['get_article']!='') {
        $json = json_decode($_REQUEST['get_article']); 
    }
    
    $node = new stdClass();
    $node->type = 'foto';
    node_object_prepare($node);
     
    $node->title = $json->title;
    $node->language = LANGUAGE_NONE;
    $node->uid = 1;
    $node->status = 1;
    $node->revision = FALSE;
    $node->comment = 0;
    $node->promote = 0;
    $node->sticky = 0;
    $node->log = NULL;
    $node->created = time();  
    
    $node->field_src_url[$node->language][0]['value'] = $json->url;
    
    $img_count = count ( $json->imgsrc);
    
    for ($i = 0; $i < $img_count; $i++) {
        $url = $json->imgsrc[$i];
        $file_info = system_retrieve_file($url, 'public://pictures/', TRUE);
        if($file_info->fid){
            $node->field_image[LANGUAGE_NONE][$i]['fid'] = $file_info->fid;
        }
    }
  
    $node = node_submit($node);
    node_save($node);
    
    drupal_goto('/node/'.$node->nid);
    return $content;
}