<?php

function imagewebimport_menu() {

  $items['admin/t'] = array(
    'title' => 'imagewebimport',
    'page callback' => 'imagewebimport_create',
   // 'page arguments' => array(1,2),
    'access arguments' => array('access content'), // whatever see above
    'type' => MENU_CALLBACK    
  );

  return $items;
}

function imagewebimport_create() {
    
    //?get_article={"title": "Online article copy", "url": "www.vvv.ue", "imgsrc": ["http://cnet4.cbsistatic.com/hub/i/r/2015/01/06/575c5dd6-d55e-44aa-b1b1-4dda78a6683d/thumbnail/770x433/fb15539c8e6988f984b81578977a6d85/mercedes-f-015-press-ces-2015-3019.jpg", "http://www.infinitiusa.com/infinitihtml/media/culture/images/future/emerg-e/mosaic/emerg-e.png", "http://www.sunshinedrugs.com/wp-content/uploads/2015/03/Fastest-Cars-Agera-R.jpg" ]}

    
    if(isset($_REQUEST['get_article']) && $_REQUEST['get_article']!='') {
        $json = json_decode($_REQUEST['get_article']); 
    }
    dsm ($json);
    
    $content = (t('Hi!'));
    
    $node_counter=0;
    
    //loop
    $node_counter++;
    $node = new stdClass();
    $node->type = 'foto';
    node_object_prepare($node);
     
    $node->title = $json->title;
    $node->language = LANGUAGE_NONE;
    $node->uid = 1;
    $node->status = 1;
    $node->revision = FALSE;
    $node->comment = 0;
    $node->promote = 0;
    $node->sticky = 0;
    $node->log = NULL;
    $node->created = time();  
    
    //JSON = diamondDetailsBodies.0.certs.0.pdf.url
    $node->field_src_url[$node->language][0]['value'] = $json->url;
    
    $img_count = count ( $json->imgsrc);
    dsm ( $img_count);
    dsm($json->imgsrc[0]);
    
    for ($i = 0; $i < $img_count; $i++) {
        $url = $json->imgsrc[$i];
        $file_info = system_retrieve_file($url, 'public://pictures/', TRUE);
        if($file_info->fid){
            $node->field_image[LANGUAGE_NONE][$i]['fid'] = $file_info->fid;//assign fid
        }
    }
  
    $node = node_submit($node);
    node_save($node);
    
    dsm($node->nid);
    
    drupal_goto('/node/'.$node->nid."/edit");
    return $content;
}